### ISSUE TITLE
Interaction with device offset buttons does nothing

### ISSUE THREAD

**Issue by ragesaq** [matzman666/OpenVR-InputEmulator#104]
I can click on enable offset, any of the +/- signs, edit them, but none of the setting actually change. They all remain the same.

**Comment by ragesaq** [comment]
I uninstalled and reinstalled 1.3 and now all is well! Yay!

**Comment by spartian** [comment]
Hello...are you able to build the code and display the input emulator ??

**Comment by crodriguezouterelo** [comment]
> I uninstalled and reinstalled 1.3 and now all is well! Yay!

Hi, I'm having the same issue. Is it still working for you?
