### ISSUE TITLE
I'd like to get in touch

### ISSUE THREAD

**Issue by JoeLudwig** [matzman666/OpenVR-InputEmulator#116]
I can't see a way to get an email address for @matzman666 so I thought I'd reach out with mine instead:
  joe@valvesoftware.com

I would like to talk about OpenVR-InputEmulator and how it interacts with the beta we're about to flip to everybody and the new binding system.

Sorry to abuse issues this way. :)

**Comment by BOLL7708** [comment]
Sure would be nice to bind the button on the Vive Tracker to trigger for easy menu handling in Beat Saber using Tracker-swords 😅 Hopefully things will work out 😗 Oh, and I'm uh, just posting to help keep the issue alive, eh.

**Comment by JoeLudwig** [comment]
The button on the Vive Tracker is rebindable (it's called "power button" and doesn't have the same restrictions as the system button.)  Depending on how Beat Saber is looking for devices, it might just work.

**Comment by BOLL7708** [comment]
That is interesting, sorry for jumping slightly off-topic, but I've tried to listen to this event myself with no real success through the C# headers for OpenVR. I noticed that a power button/similar is not listed in the types of buttons for controllers [here](https://github.com/ValveSoftware/openvr/blob/master/headers/openvr.h#L728) but perhaps I'm looking in the wrong place or for the wrong thing. In my application I output all queued events and get nothing from a Tracker except if it's idling or not 😅

**Comment by Lhun** [comment]
Hi Joe, from what I understand matzman struggles a little with overwork, he's expressed this on reddit a few months back. It might be worth it to fork ovr-inputemulator with his blessing and allow people like myself, greg with driver4vr and kinceryn and others who want to create openvr compatable tracking solutions by making the ability to emulate trackers part of steamvr.

**Comment by JoeLudwig** [comment]
@BOLL7708 : You'll need to use the new input system. The old input system supports more or less just what was on an original Vive wand. You can find an updated Unity plugin here: https://github.com/ValveSoftware/steamvr_unity_plugin/releases  Or see the latest SDK: https://github.com/ValveSoftware/openvr/releases/tag/v1.0.15

@lhun : Good to know. I'm not so much looking to fork OpenVR Input Emulator so much as try to see if the new SteamVR Input system is meeting people's needs. And to try to avoid the scramble that happened back in January when we updated and inadvertently broken it. Because of the way OpenVR Input Emulator works, we can't really avoid breaking it from time, but at least we can be coordinated about it. :)

I reached out on Reddit. We'll see if that bears fruit. Thanks, everybody!

**Comment by Lhun** [comment]
If it would be possible to pass abstraction to openvr in a way that would
allow things like the more affordable perception neuron or a kinect out of
the box that would be amazing, lots of hungry vrchat users out there want
full body. Plus then devs would know they could add those capture features
to their games and have an audience for them.
