### ISSUE TITLE
Motion Compensation with SteamVR 1.1.3

### ISSUE THREAD

**Issue by TalonSim** [matzman666/OpenVR-InputEmulator#134]
Tested on 3 computers.  SteamVR update 1.3.3 disrupts communication with Input Emulator.  I repeatedly get the message "could not set device mode: unknown error" whenever I try to apply a device mode.  I have tried the fix for issue #133 with no luck.  i'm wondering if anyone has ideas for a fix, or a short term workaround.

**Comment by SplitPixl** [comment]
I finally figured out why my fix wasn't working for other people, explained breifly [here](https://github.com/matzman666/OpenVR-InputEmulator/pull/130#issuecomment-442684934). That workaround should work now.

**Comment by TalonSim** [comment]
Thanks, That update did the trick. Back up and running

**Comment by agroumqc** [comment]
Just some more precision for those who are less familiar

try that  https://github.com/matzman666/OpenVR-InputEmulator/issues/170#issuecomment-531426234
