### ISSUE TITLE
Unable to get motion cancellation working.... is it broken as a utility?

### ISSUE THREAD

**Issue by ncleme** [matzman666/OpenVR-InputEmulator#143]
I have a Vive Pro and DOF P3. I have been trying to get openvr Input Emulator to work. I have tried both standard and beta version of Steam VR. But when I try and follow the guide by JMB3d, I get to the part when you choose the motion compensator settings selecting Set Zero.. then it just jumps out of menu back to the vr dashpanel now without the button for openvr emulator ?????? any help would be greatly appreciated

**Comment by trueA1M2** [comment]
Have you patched in the hopefully files

**Comment by trueA1M2** [comment]
I have the same set up its a bitch to get going but well worth it

**Comment by trueA1M2** [comment]
https://github.com/matzman666/OpenVR-InputEmulator/files/2627370/driver_vrinputemulator_release_hopefully.zip

**Comment by trueA1M2** [comment]
Download unzip and copy and paste the whole thing here 'drive':\Steam\steamapps\common\SteamVR\drivers\vrinputemulator remove the old folder somewhere first then I have to delete this file C:\Users\'your folder'\App data\Local\openvr\openvrpaths.vrpath
also you have to make a folder exception in windows defender or your anti virus I did this for 'drive':\Program files\OpenVR-InputEmulator also 'drive'Program Files (x86)\SimTools also 'drive'\Steam
note. If my PC is running and I plug everything in ie. wheel, chair, rear speakers, htc vive, the emulator has a conflict so I have to plug in and restart, I think its just my conflict though.

**Comment by trueA1M2** [comment]
As for the physical setup I didn't want to move my trackers or buy more controllers and this works 100%![motion compensation](https://user-images.githubusercontent.com/45529434/51174403-9e8e9a80-18af-11e9-826c-49c3afc3cff7.jpg)

**Comment by ncleme** [comment]
Thankyou for the advice I will try again tonight....  One point:- Is it important to be in game before connecting to steam Vr and selecting openvr emulator settings etc !!!

**Comment by trueA1M2** [comment]
Start steam vr inside the headset choose openVR from menu select controller and edit

**Comment by trueA1M2** [comment]
edit your files before starting anything, vr games won't let you start without vr running on steam but yes always vr first, edit controller run game etc?

**Comment by ncleme** [comment]
Very very big thankyou :)  all working fine, .. very happy... again many thanks....

**Comment by UeflaVR** [comment]
And it´s not possible to go back to an old version of SteamVR?

**Comment by vcortex91** [comment]
This worked, thanks trueA1M2.

**Comment by trueA1M2** [comment]
Your welcome 
Since upgrading to buttkickers I have used alot of foam around the vive controller 👍
