### ISSUE TITLE
Selecting "Input Remapping" crashes application

### ISSUE THREAD

**Issue by evilC** [matzman666/OpenVR-InputEmulator#169]
If I select a vive controller and click "Input Remapping", there is a slight pause, then OIE closes and the icon disappears from the menu.  
If I select the headset, I can enter the menu, but obviously it has no inputs
![](https://i.imgur.com/IPtVw82.png)

**Comment by agroumqc** [comment]
Hi try that 

https://github.com/matzman666/OpenVR-InputEmulator/issues/170#issuecomment-531426234

**Comment by evilC** [comment]
Fixed, thank you
