### ISSUE TITLE
Valve Index Controllers - Crashes when selecting Input Remapping - Error Code 6

### ISSUE THREAD

**Issue by Claw256** [matzman666/OpenVR-InputEmulator#197]
I'm trying to get this program to work with my Index and Knuckles Controllers, but it seems to be crashing every time that I press the Input Remapping Button on either the SteamVR overlay, or the desktop program mode. An error message also shows up when I select the controller, and press Apply next to Device Mode, it shows up the message "Could not set device mode: Unknown Error". Then if I select a different Device Mode, it shows up with the error "Could not set device mode: Device Not Found". I have tried a lot, and I can't seem to get the program to work. I have tried sharkyh20's fork on GitHub, with the DLL, and that didn't seem to work either ([https://github.com/sharkyh20/openvr-inputemulator/releases](https://github.com/sharkyh20/openvr-inputemulator/releases)). I have tried disabling the camera, I've tried uninstalling SteamVR and reinstalling it, I've tried reinstalling the OpenVR-InputEmulator, and I still have the problem.

I'm on SteamVR Beta v1.14.12, with Valve Index and Valve Knuckles Controllers.

Here is the log output next to the `driver_vrinputemulator.log`, located in `Steam\steamapps\common\SteamVR\drivers\00vrinputemulator\bin\win64`:

```
[ERROR] 2020-09-15 00:28:10: Error while updating device button mapping: Error code 6
[ERROR] 2020-09-15 00:28:10: Error while updating device button mapping: Error code 6
[ERROR] 2020-09-15 00:28:10: Error while updating device button mapping: Error code 6
[INFO ] 2020-09-15 00:28:11: Client disconnected: clientId 7
[INFO ] 2020-09-15 00:28:13: New client connected: endpoint "driver_vrinputemulator.client_queue.198789112", cliendId 8
[ERROR] 2020-09-15 00:28:13: Error while updating device button mapping: Error code 6
[ERROR] 2020-09-15 00:28:13: Error while updating device button mapping: Error code 6
[ERROR] 2020-09-15 00:28:13: Error while updating device button mapping: Error code 6
[ERROR] 2020-09-15 00:28:13: Error while updating device button mapping: Error code 6
[ERROR] 2020-09-15 00:28:15: Error while updating device button mapping: Error code 6
[ERROR] 2020-09-15 00:28:15: Error while updating device button mapping: Error code 6
[ERROR] 2020-09-15 00:28:15: Error while updating device button mapping: Error code 6
[ERROR] 2020-09-15 00:28:15: Error while updating device button mapping: Error code 6
[ERROR] 2020-09-15 00:28:16: Error while triggering haptic pulse: Error code 6
[ERROR] 2020-09-15 00:28:16: Error while updating device button mapping: Error code 6
[ERROR] 2020-09-15 00:28:16: Error while updating device button mapping: Error code 6
[ERROR] 2020-09-15 00:28:16: Error while updating device button mapping: Error code 6
[ERROR] 2020-09-15 00:28:18: Error while updating device button mapping: Error code 6
[ERROR] 2020-09-15 00:28:18: Error while updating device button mapping: Error code 6
[ERROR] 2020-09-15 00:28:18: Error while updating device button mapping: Error code 6
[ERROR] 2020-09-15 00:28:19: Error while updating device button mapping: Error code 6
[ERROR] 2020-09-15 00:28:19: Error while updating device button mapping: Error code 6
[ERROR] 2020-09-15 00:28:19: Error while updating device button mapping: Error code 6
[ERROR] 2020-09-15 00:28:21: Error while updating device button mapping: Error code 6
[ERROR] 2020-09-15 00:28:21: Error while updating device button mapping: Error code 6
[ERROR] 2020-09-15 00:28:21: Error while updating device button mapping: Error code 6
[ERROR] 2020-09-15 00:28:22: Error while updating device pose offset: Error code 6
[ERROR] 2020-09-15 00:28:22: Error while updating device button mapping: Error code 6
[ERROR] 2020-09-15 00:28:23: Error while updating device button mapping: Error code 6
[ERROR] 2020-09-15 00:28:23: Error while updating device button mapping: Error code 6
[ERROR] 2020-09-15 00:28:23: Error while updating device button mapping: Error code 6
[ERROR] 2020-09-15 00:28:23: Error while getting digital input remapping: Error code 6

```
![ovr-emu-error](https://user-images.githubusercontent.com/31168189/93148169-11868f00-f6eb-11ea-8fcb-d89ed203143b.png)
![ovr-emu-error-2](https://user-images.githubusercontent.com/31168189/93148176-151a1600-f6eb-11ea-8c9f-64e3e86a3de6.png)

If anyone can help me with this problem, I would very much appreciate it.

**Comment by fwenny** [comment]
#198 check this one, someone provided a new dll that fixed input emulator.

**Comment by thoskee** [comment]
If that doesn't work for you, I had similar issues when I had either camera on, or camera on controller, but for some strange reason, if I used the button on the lower left of the HMD (there is one, never knew it was even there lol) it would open the same dashboard, but didn't crash it.

**Comment by Claw256** [comment]
> #198 check this one, someone provided a new dll that fixed input emulator.

This has fixed my issue, Thanks @fwenny :)

Edit: This is the post that you were referring to: https://github.com/matzman666/OpenVR-InputEmulator/issues/198#issuecomment-695218855
