### ISSUE TITLE
Broken again since last SteamVR update? (1.18.7)

### ISSUE THREAD

**Issue by animemoko** [matzman666/OpenVR-InputEmulator#216]
The program closes when loading an offset profile :(

**Comment by trueA1M2** [comment]
Dont use this anymore use OpenVR-MotionCompensation_0_3_5 turn the filters down !

**Comment by animemoko** [comment]
It's working back again for some reason.
I use InputEmulator for adjusting the offset position of the controllers, motion compensation doesn't do that. If you know any other program that does, let me know.
