### ISSUE TITLE
Can't use it even with fix 

### ISSUE THREAD

**Issue by Haha-funny** [matzman666/OpenVR-InputEmulator#217]
I deleted all VR related folders in Appdata and reinstalled everything that had anything to do with VR and put in the latest fixed dll
nothing has changed. i really hope someone can help me thanks

**Comment by trueA1M2** [comment]
Dont use this anymore use OpenVR-MotionCompensation_0_3_5 turn the filters down !

**Comment by Haha-funny** [comment]
That doesn't help me as there is no way to set offsets or any of the other features in OVRIE but thanks for trying to help !

**Comment by Haha-funny** [comment]
It started working again for no apparent reason . If anyone else is having problems with this just Uninstall it and delete the following directories : C:\Program Files\OpenVR-InputEmulator , C:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\00vrinputemulator , C:\Users\Username\AppData\Roaming\matzman666 and every file related to OVRIE and then just do a fresh install. I don't know what the issue was but just waiting a few weeks worked for me.
