### ISSUE TITLE
Button mapping across devices

### ISSUE THREAD

**Issue by peroht** [matzman666/OpenVR-InputEmulator#22]
Would it be possible to have button mapping across different devices?

**Comment by migero** [comment]
just use freepie to emulate hydra and add any mapping to that then in InputEmulator set to replicate

**Comment by peroht** [comment]
Yes thats absolutely a good suggestion. I just want to minimize the amount of middleware in the loop :)

**Comment by migero** [comment]
if you need any help on hydra in free pie

its using

	hydra[1].start = right1.value
	hydra[1].one = right1.value
	hydra[1].two = right2.value
	hydra[1].three = right3.value
	hydra[1].four = right4.value
	hydra[1].bumper = rightBumper.value
	hydra[1].joybutton = rightJoystickButton.value
	hydra[1].start = rightMiddle.value
	hydra[1].joyx = rightJoystickX.value
	hydra[1].joyy = rightJoystickY.value
	hydra[1].trigger = rightTrigger.value

and so on

**Comment by peroht** [comment]
This is replaced by the new IVRInput system. Closing.
