### ISSUE TITLE
1.1 Oculusfix2 - Crashing input mapping

### ISSUE THREAD

**Issue by romkslrqusz** [matzman666/OpenVR-InputEmulator#45]
Both of the Oculusfix releases started crashing, on both beta and non-beta steamvr.

It happens when I choose "input mapping" and causes the OpenVR-InputEmulator to disappear from SteamVR.

**Comment by poyungan** [comment]
I am having the same problem. It seems several others are too.
I have tried both beta and non-beta steamvr. I have installed and uninstalled several times.

**Comment by romkslrqusz** [comment]
What used to be beta may have been pushed live, breaking this.

Shame there is no way to roll back :/

**Comment by poyungan** [comment]
In the Steam VR overlay the Touch controllers can be identified and vibrate. In the Input settings when  in VR they cannot be identified and do not vibrate. 

If the Beta is now live wouldn't there be a lot more people now having issues?

So frustrating.

**Comment by romkslrqusz** [comment]
Good point.

Yeah, it's driving me crazy. Funny thing is I was using it without issue the day before.

Are you on Oculus Dash? Perhaps an update to that is what broke things.

**Comment by poyungan** [comment]
I had not used the Rift for about 9 months and reinstalled everything on  a new rig so I assume all are the latest updates.
That is curious that you had it working and now stopped. You can't remember if you changed anything?

**Comment by romkslrqusz** [comment]
Only change was trying to install oculusfix version 2 - and reverting that change left it with the same behavior

**Comment by Eraile** [comment]
Hey guys, it crashes because there must have been a SteamVR update that broke the way the VR Input Emulator talks to Steam... and it makes it crash... It needs a fix. Sadly idk how to help with that.

**Comment by romkslrqusz** [comment]
@Eraile I thought that might be the case, but reports of this issue aren't super widespread (yet?)

**Comment by poyungan** [comment]
I tried the new Steam VR Beta; no luck.

**Comment by rekaXua** [comment]
Have the same issue. By some miracle I even get it to work for 1 day, just before the SteamVR update, but can't anymore.
Here is a part of log file (I've just censored a part of serial, and what interesting, serial is the same):

[INFO ] 2017-12-21 00:31:35: Application started
[INFO ] 2017-12-21 00:31:35: Log Config: D:\Program Files\OpenVR-InputEmulator\logging.conf
[INFO ] 2017-12-21 00:31:35: Log File: C:/Users/Alexander_rekaX/AppData/Roaming/matzman666/OpenVRInputEmulator/VRInputEmulator.log
[INFO ] 2017-12-21 00:31:35: Desktop mode enabled.
[INFO ] 2017-12-21 00:31:35: Sound effects disabled.
[INFO ] 2017-12-21 00:31:35: Settings File: C:/Users/Alexander_rekaX/AppData/Roaming/matzman666/OpenVRInputEmulator.ini
[INFO ] 2017-12-21 00:31:37: VR Runtime Path: C:/Steam/steamapps/common/SteamVR/
[INFO ] 2017-12-21 00:31:37: sizeof(DigitalBinding) = 28
[INFO ] 2017-12-21 00:31:37: sizeof(DigitalInputRemapping) = 108
[INFO ] 2017-12-21 00:31:37: sizeof(AnalogInputRemapping) = 36
[INFO ] 2017-12-21 00:31:37: sizeof(ipc::Request) = 312
[INFO ] 2017-12-21 00:31:37: sizeof(ipc::Request::msg) = 296
[INFO ] 2017-12-21 00:31:37: sizeof(ipc::Reply) = 304
[INFO ] 2017-12-21 00:31:37: sizeof(ipc::Reply::msg) = 280
[ERROR] 2017-12-21 00:31:41: Could not connect to driver component: Could not open server-side message queue: boost::interprocess_exception::library_error
[ERROR] 2017-12-21 00:31:41: Exception caught while getting device info: No active connection.
[INFO ] 2017-12-21 00:31:41: Found device: id 0, class 1, serial WMHD314xxx0ZXE
[ERROR] 2017-12-21 00:31:41: Exception caught while getting device info: No active connection.
[INFO ] 2017-12-21 00:31:41: Found device: id 4, class 2, serial WMHD314xxx0ZXE_Controller_Left
[ERROR] 2017-12-21 00:31:41: Exception caught while getting device info: No active connection.
[INFO ] 2017-12-21 00:31:41: Found device: id 5, class 2, serial WMHD314xxx0ZXE_Controller_Right
[ERROR] 2017-12-21 00:31:41: Exception caught while getting device info: No active connection.
[ERROR] 2017-12-21 00:31:43: Exception caught while getting device info: No active connection.
[ERROR] 2017-12-21 00:31:43: Exception caught while getting device info: No active connection.
[ERROR] 2017-12-21 00:31:43: Exception caught while getting device info: No active connection.
[ERROR] 2017-12-21 00:31:43: Exception caught while getting device info: No active connection.

But the most interesant is this: "[ERROR] 2017-12-21 00:31:41: Could not connect to driver component: Could not open server-side message queue: boost::interprocess_exception::library_error"

**Comment by rekaXua** [comment]
Oh, I've fixed it. The issue was: 
"Known Bugs:
The shared-memory message queue is prone to deadlock the driver when the client crashes or is exited ungracefully."
So by some demonic combination of rebooting and reinstalling Input Emulator I've managed to get it back to work!

**Comment by poyungan** [comment]
rekaXua, congratulations!
Now please tell me what Steam VR version you are using and exactly what steps you took and I will be forever in your debt.
Did you reinstall the Oculus software at all?

**Comment by romkslrqusz** [comment]
I was able to get mine working again thanks to @rekaXua !
@poyungan I shut down Steam and the Oculus Service while doing this, and did each reboot by hitting Alt+F4 from the desktop. Using the current, non-beta version of Steam. Uninstall OVRInputEmulator, reboot, install it again, reboot, and then it should work.

**Comment by poyungan** [comment]
Great news! I will try as soon as I get home. Thanks to you both.

**Comment by poyungan** [comment]
Still no joy.
When you reinstall the Emulator then reboot, what do you start to open Steam VR? The Emulator.exe or open Steam VR directly.
If i do the latter, the VR Input Emulator button does not show in the VR menu, only if I open through the Emulator.exe.
Could you please tell me what settings you have in Steam VR?

**Comment by rekaXua** [comment]
You can try to launch Emulator in desktop mode, bud don't even try to launch it from .exe, because it's kinda breaks stuff. And from my experience, if you don's see a Emulator button in VR - it's a good sign.

**Comment by poyungan** [comment]
I am a bit confused. What do you mean by Desktop mode and how can you change the inputs if the Emulator button is not showing?

**Comment by romkslrqusz** [comment]
@poyungan You should not have to manually launch the emulator.

Fire up any SteamVR game, and bring up the SteamVR menu. You should have a row of orbs towards the bottom - Mine are SteamVR, OpenVR AdvancedSettings, and OpenVR Input Emulator.

I'm going to close this issue since a workaround was found.

Resolved by uninstalling and reinstalling the software, with system restarts after each step.
