### ISSUE TITLE
Stopped working today

### ISSUE THREAD

**Issue by surfingtheworld** [matzman666/OpenVR-InputEmulator#51]
Hello! Thanks for creating this. Was working really well. Now for some reason steam VR hangs  when I try and select a controller to remap. The VR emulation option then disappears until I reload steam VR

**Comment by rekaXua** [comment]
https://github.com/matzman666/OpenVR-InputEmulator/issues/45

**Comment by WarReapers** [comment]
#45 does not work as a fix for 1.2 I have the same issue and have tried uninstalling and reinstalling many times

**Comment by jasonbdj** [comment]
Same problem, followed 45 but nothing....even in desktop mode :/

**Comment by jasonbdj** [comment]
check out #59, seems there is a fix. SteamVR has been updated and broke the emulation but there is a fix.

**Comment by matzman666** [comment]
New version is out that restores compatibility with all current SteamVR branches.
