### ISSUE TITLE
Saved profile applies wrong input remapping

### ISSUE THREAD

**Issue by blinkVR** [matzman666/OpenVR-InputEmulator#52]
Hello!

I've repeatedly tried to rebind the right application button to the keyboard press "V" and save it in a profile, but whenever I apply this profile the button remapping will turn into "Shift+Alt+Ctrl+V" instead of just "V".

Happens regardless of restarting SteamVR or applying the profile right away after saving it.

Other input remapping like the Fallout 4 related fixes (deadzone fix, etc) seem to get saved properly

Tested on 1.1 and 1.2.
Latest stable SteamVR branch
Hardware: Oculus Rift + Touch

Edit: additionally sometimes the saved remapping will turn into "Shift+Alt+CTR + 'None'" when applying the saved profile.

**Comment by FolkSong** [comment]
Exact same problem here (even down to the use of 'V'). I've also seen it get restored as 'ctrl+alt+shift+space' after a fresh restart of SteamVR.

**Comment by Japander75** [comment]
Same problem with Vive, very simple "right application" button profiles are not saving correctly.

**Comment by xermalk** [comment]
Bump, experiencing this to.
This is mildly annoying when setting up a VATS replacer in FO4VR.

**Comment by DawsSangio** [comment]
Same here, very annoying.

**Comment by matzman666** [comment]
Fixed in the newest version.
