### ISSUE TITLE
Feature request: OpenVR Tools

### ISSUE THREAD

**Issue by r57zone** [matzman666/OpenVR-InputEmulator#6]
Program that allows configure through the GUI (how on OpenTrack, Xbox360ce) controllers or hmd position (head tracking).
**Head tracking input** :  OpenTrack (Output UDP sender), Xbox input stick, Manual (UDP or TCP port for accelerometer, gyroscope, magnetometer).

**Contollers input** : Xbox controller[[1]](https://www.youtube.com/watch?v=UZNttWbTiu4), Daydream Controller[[1]](https://hackernoon.com/how-i-hacked-google-daydream-controller-c4619ef318e4)[[2]](https://www.youtube.com/watch?v=Y54b76S3NEg)[[3]](https://i.imgur.com/yWFCsG5.png)[[4]](https://i.imgur.com/M0V8Q7I.jpg), Manual (UDP or TCP port for accelerometer, gyroscope, magnetometer and buttons).

Thanks.

**Comment by matzman666** [comment]
I don't quite understand. Do you want to use the sensor data from different sources to control the orientation of the Vive headset/controller, or do you want to use the sensors data from the Vive headset/controller in other applications? Is the screenshot from a GUI mockup you made, or from an existing tool?

**Comment by r57zone** [comment]
Yes, data from different sources for tracking in OpenVR. For example, FreePie IMU from Android for HMD orientation on OpenVR or Xbox input for emulation vive controllers on OpenVR.

Screenshot is a layout, so it was clearer what I mean.

Inputs: FreePie, Xbox controller, Daydream controllers
Output: OpenVR HMD orientation, OpenVR vive controllers.

**Comment by matzman666** [comment]
My next major goal is integration into FreePIE, this should allow you to write FreePIE scripts that implement your use cases.

**Comment by r57zone** [comment]
[FreePIE for PC](https://github.com/simlrh/FreePIE-OSVR) already exist, I did not manage to make it work. It's better to make support FreePie IMU or Wireless IMU (Android applications) for HMD head tracking.

**Comment by matzman666** [comment]
> FreePIE for OSVR already exist, I did not manage to make it work. 

I plan to make my own fork of FreePIE, which will work as soon as I am finished.

**Comment by r57zone** [comment]
@matzman666 Maybe sample api like [this](https://github.com/TrueOpenVR/TrueOpenVR-Core/blob/master/Library/%D0%A1%2B%2B/TrueOpenVR.h) functions called from dll.

**Comment by JabberwockPL** [comment]
Forking of FreePIE might not be optimal, as new stuff in the main branch could be used in your project. For example, only recently we got Balance Board support in FreePIE, which would be great to use as a walking input in VR (I am already doing that in VRidge).

**Comment by r57zone** [comment]
I made a [driver for HMD](https://github.com/r57zone/OpenVR-OpenTrack), which is installed very simply. Supports FreeTrack and OpenTrack. I also made a standard [TrueOpenVR](https://github.com/TrueOpenVR) that is even more convenient for DIY HMD.

**Comment by kblood** [comment]
Wow.. very interesting r57zone.

**Comment by r57zone** [comment]
I did something similar in the [TrueOpenVR](https://github.com/TrueOpenVR) project.
