### ISSUE TITLE
3dRudder Support 

### ISSUE THREAD

**Issue by 3DRSenior** [matzman666/OpenVR-InputEmulator#60]
Happy New Year. 

I sent you an email, but i did not get any response yet. 
I would like to be able to work with you add the 3dRudder compatibility in your nice projet. 
(i can send you a 3dRudder) 

Thank you

**Comment by matzman666** [comment]
Oh, sorry. Your last email got lost in the shuffle of the christmas season. 

Adding 3dRudder support shouldn't be too hard. If I understood it correctly the 3dRudder is basically a 4-axis joystick you control with your feet. To simulate physical movement in any VR application I just need to assume that the axis values of the 3dRudder represent the speed the user moves along configurable translation or rotation axis of the VR universe, and continuously add offsets to the headset and controllers accordingly. At least that's the theory, how well it works in practice and how games react when the users appear several hundred meters or even kilometers away from the playspace bounds is another question (e.g. as fas ar I know Onwards checks the distance of the user from the playspace center as anti-cheat measure). But we will never know without trying.

All required functionality should already be implemented in Input Emulator, although I probably need to refine some things to enhance user experience. I see you also provide a C++ SKD, so a simple client that connects to the Input Emulator driver and emulates physical movement should be very easy to write. If you send me a device I can definitely do that, and then see how to continue from there based on the gathered experience. You can contact me via matzman(at)matzman.net to discuss about further details.

**Comment by 3DRSenior** [comment]
i respond by email :) look forward to talk with you
