### ISSUE TITLE
Audio Bell interfering with gameplay.

### ISSUE THREAD

**Issue by LiquidSmokeX64** [matzman666/OpenVR-InputEmulator#63]
Okay.. for One, there's a notice for you to update this app from Steam.
Secondly, the way this is it's unplayable with anything. Attempting to play FO4VR on Rift before even getting into the title screen the Bell sound is going off so frequently you CANNOT EVEN HEAR THE GAME over the ringing. NOT COOL dude.

**Comment by matzman666** [comment]
In the newest version I tuned down the volume of the audio cue. If you still don't like it, the audio file is located in *[SteamVR-Installation-Directory]\drivers\00vrinputemulator\resources\sounds*. Replace it with an audio file you like, or delete it for no sound at all.

**Comment by LiquidSmokeX64** [comment]
Thanks for the quick response. I will get the newest version and see how it
goes. Hopefully it works with the newest steam vr stable release.

**Comment by LiquidSmokeX64** [comment]
So.. another bug report.
Now after configuration for FO4VR (track pad fix) I'm finding it almost
impossible to click and actually "activate" pretty much everything.
Any thoughts?
